easy_admin:
    user:
        display_name: true
        display_avatar: false
        name_property_path: 'email'
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        - App\Entity\User
    design:
        brand_color: '#1ABC9C'
